### ISSUE TITLE
Handle no internet connectivity

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#10]
#### What steps will reproduce the problem?
1. Disconnect from the internet
2. Run the application and try to rename a file
3. Get a SocketExpception
#### What is the expected output? What do you see instead?

Should handle it gracefully with an error message box and option to close
the application

**Comment by Spaceherpe** [comment]
How do I locate the executable version of 0.3? I don't know how to employ the source code files.

**Comment by Spaceherpe** [comment]
Sorry, correction, 0.7.3

**Comment by vipuldelwadia** [comment]
You can always download the latest release of TVRenamer from the official site: http://tvrenamer.org/

The version @daveharris refers to was 0.3, which was released quite a while ago and there have been many releases since then. The current release is 0.7.2 which you can find here: https://github.com/tvrenamer/tvrenamer/releases/tag/0.7.2
