### ISSUE TITLE
configuration files

### ISSUE THREAD

**Issue by johnv02139** [tvrenamer/tvrenamer#120]
I suggest having a configuration directory.  In my branch, I made ~/.tvrenamer be a directory, and moved the file ~/.tvrenamer to ~/.tvrenamer/prefs.xml, and .tvrenameroverrides to ~/.tvrenamer/overrides.xml.  I wrote a little code that would convert an existing home directory to the new format.

Right now it's kind of in the middle of my branch, but if you like this idea I can pull it out and make it mergeable.

**Comment by lsrom** [comment]
I like it but before pulling to main repo, we should check if yur conversion code works on Windows/MacOS. Switch from files to directory should be invisible to the end user I think, so conversion code needs to work on all platforms.

**Comment by johnv02139** [comment]
I've tested on Windows and Mac OS.  All of Java's file functionality is platform independent.

**Comment by vipuldelwadia** [comment]
This is fine, I think Java has APIs (at least in java.nio) for getting at the config directory or similar - we should use those where appropriate.

I general I think having one pull-request per feature/functionality is good (rather than lots of changes in one), so you should pull out this change from your branch and submit it separately.

**Comment by eprenamer** [comment]
Resolved in #156
