### ISSUE TITLE
Two new features/options

### ISSUE THREAD

**Issue by rodrigograca31** [tvrenamer/tvrenamer#130]
Hi!

Loved the program! (run-linux.sh din't work but I got it working...)

I would like to ask for two new features:

1. Option to not rename the files... (just move them) As of now we can enable/disable the "move option", I would like to be able to enable/disable the "rename option" ... Because I just wanted to use this program to automatically move my files to the "Show-->Season" folders...
2. New rename token: "Quality" ... I have a lot of diferente qualities per season/show ... I have for example: Episode 1 in 720p and Episode 2 in 1080p... this program doesn't allow me to show/write that (720p or 1080p) in the file name .... Genesis or others will probably show me some HD symbol or other thing but when I look at the files I don't know which ones I have in HD or not....

Thanks!

**Comment by lsrom** [comment]
Hi,

number 2 is already implemented, it's called Resolution. Check it out in User preference.

run-linux.sh has Windows line endings I think, to fix it use dos2unix or something similar.

As far as your first feature request, I don't have the TVRenamer installed currently, but try setting replacement token to empty. It could do exactly what you want it to, until someone has the time to properly code it. I'm not sure though, because I haven't looked at this code for very long time :) so it might not work.

**Comment by rodrigograca31** [comment]
![image](https://cloud.githubusercontent.com/assets/1134310/22835851/0fb69e48-efb2-11e6-8074-d5a16eea573b.png)
I can't see "Resolution" in the list ... `v0.7.2`

Setting the replacement token to empty doesn't do what you thought it would: (it renames the file to a file with no name...)
![image](https://cloud.githubusercontent.com/assets/1134310/22836047/e20e9544-efb2-11e6-872c-329ac7adf0d9.png)

**Comment by eprenamer** [comment]
As @lsrom suggested, to see %r in the rename box, you need to get an updated version.  Presumably that means checking out the source and building it yourself.

I thought #1 was a good idea, so I took a pass at implementing it, in my branch "justmove".  I'll put in a pull request, but the maintainers don't have much time for this project any more.

**Comment by rodrigograca31** [comment]
@eprenamer Great!
I don't want to compile this project... (not that important)
I hope they accept your PR...

**Comment by daveharris** [comment]
Hi,
Thanks for the Pull Request @eprenamer. It's all merged in an will be released in version `0.8`.
There are a few other fixes so we'll push this out soon.
Sorry about the delay

Dave

**Comment by rodrigograca31** [comment]
@daveharris That's great!

**Comment by daveharris** [comment]
Hi @rodrigograca31,
I just thought that I would give you a quick update on this and version `0.8`. Overnight, @eprenamer put in a huge [Pull Request](https://github.com/tvrenamer/tvrenamer/pull/141) which cleans up the code *a lot*. I would really like this to be part of the `0.8` release so that we advance forwards and not just let it sit.
This may mean that the release may be a little delayed to merging this in and making sure nothing breaks but I think it's for the good of the project.
Hopefully you are ok with this (given you've had to wait thing long!)

Dave

**Comment by rodrigograca31** [comment]
@daveharris dont worry, take your time.
The version I have is working fine :)
Thanks.

**Comment by eprenamer** [comment]
Resolved in #134

**Comment by eprenamer** [comment]
We're still working on getting the release out, but you could try a prerelease from here:

https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0b3

**Comment by eprenamer** [comment]
@rodrigograca31 These are present in v0.8, which is now released:

https://github.com/tvrenamer/tvrenamer/releases/latest

**Comment by rodrigograca31** [comment]
@eprenamer looks awesome!
