### ISSUE TITLE
Automation Request

### ISSUE THREAD

**Issue by Spaceherpe** [tvrenamer/tvrenamer#131]
I'm wondering if it is at all possible to assign a designated folder to monitor and create an automation script that when new files are identified, they be renamed and moved automatically. Perhaps with a scan timer to check ever 30 minutes or so? Or perhaps with an adjustable timer?

**Comment by daveharris** [comment]
Hi,
We have a console version of the application which is in beta which you might like to try. See #76 for downloads and details.

Thanks!
Dave

**Comment by Spaceherpe** [comment]
Can't log into the linked site you posted. Also, it looks as if it's asking for money?

**Comment by vipuldelwadia** [comment]
The site @daveharris linked is another page on this site you're currently on (github.com) - this site doesn't ask for money or anything. That sounds like your computer or browser is infected with some kind of virus or malware - I suggest doing a full scan of your computer using an anti-malware tool.

**Comment by davekeane** [comment]
Looks like drone.io, linked from the page @daveharris linked to, is down
now though.

On Mon, 13 Mar 2017, 18:12 Vipul Delwadia, <notifications@github.com> wrote:

The site @daveharris <https://github.com/daveharris> linked is another page
on this site you're currently on (github.com) - this site doesn't ask for
money or anything. That sounds like your computer or browser is infected
with some kind of virus or malware - I suggest doing a full scan of your
computer using an anti-malware tool.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tvrenamer/tvrenamer/issues/131#issuecomment-286017055>,
or mute the thread

**Comment by Spaceherpe** [comment]
No viruses


Sent via the Samsung Galaxy S®6 active, an AT&T 4G LTE smartphone
-------- Original message --------From: davekeane <notifications@github.com> Date: 3/13/17  01:59  (GMT-05:00) To: tvrenamer/tvrenamer <tvrenamer@noreply.github.com> Cc: Spaceherpe <spaceherpe@gmail.com>, Author <author@noreply.github.com> Subject: Re: [tvrenamer/tvrenamer] Automation Request (#131) 
Looks like drone.io, linked from the page @daveharris linked to, is down

now though.



On Mon, 13 Mar 2017, 18:12 Vipul Delwadia, <notifications@github.com> wrote:



The site @daveharris <https://github.com/daveharris> linked is another page

on this site you're currently on (github.com) - this site doesn't ask for

money or anything. That sounds like your computer or browser is infected

with some kind of virus or malware - I suggest doing a full scan of your

computer using an anti-malware tool.



—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub

<https://github.com/tvrenamer/tvrenamer/issues/131#issuecomment-286017055>,

or mute the thread

**Comment by vipuldelwadia** [comment]
Ah my mistake, I didn't realise drone.io had gone down. I will try to make a build available of the console version soon from another host.
