### ISSUE TITLE
use java nio files

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#142]
The old java.io.File class is much despised and has numerous problems.  The nio package is much better, as long as you're willing to require Java 7, which TVRenamer already does.

This is such a File-oriented program, the upgrade is not trivial.  I've done it in my branch, although it's somewhat intertwined with other changes.  I can try to re-order things to present just the changes to NIO, if you'd be interested.

**Comment by vipuldelwadia** [comment]
I am on board with this in theory, just have a few concerns around the FileUtilities in https://github.com/tvrenamer/tvrenamer/tree/master/src/main/org/tvrenamer/controller/util.

Actually, it'd be good to be able to use Java's nio for that information (progress of file moving) so that we can remove this code 😄

**Comment by eprenamer** [comment]
Resolved in PR #158
