### ISSUE TITLE
eliminate internet proxy?

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#173]
Are the proxy settings really useful at this point?  By now, even computers that aren't directly connected to the Internet have any kind of configuration done at the OS level, don't they?

Are there objections to removing this code?  @vipuldelwadia @daveharris

**Comment by daveharris** [comment]
I added it because at the time my employer required an http proxy which meant that I unable to develop or test at work. I have no idea idea how often it's used, we have no way of knowing. I doubt that many people wanting to rename to files have a proxy though.

I doubt there is a platform-independent way of getting proxy information but there may be some Java API.

If not yeah then I guess we can get ride of it and cleanup cyrpto tools as well

Dave
________________________________

**Comment by eprenamer** [comment]
The cryptography stays out of the way, but the proxy has a UI and messages with the user about things like "check your proxy settings."  But if it's useful to you, let's leave it as is, at least for now.

**Comment by daveharris** [comment]
It *was* useful to me at the time, but that was 2 jobs and 8+ years ago. Ditch it!

**Comment by eprenamer** [comment]
Removed and resolved in PR #195
