### ISSUE TITLE
ship it?

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#201]
I think I've done about all I want to do for this release.  There's tons more I want to do, but I'm going to start a new branch for a new version.  Is there anything else anyone else thinks needs to go in for 0.8b1?

**Comment by daveharris** [comment]
Wow @eprenamer you've done so much work, it's barely the same (neglected) app it used to be!

I'm all for pushing out a beta release. I don't know if many people will actually download the beta, but it's certainly worth it.

When we release for real, there are few manual steps, such as updating http://tvrenamer.org/version which is currently `0.7.2`. I'm pretty sure @vipuldelwadia is the only one with access. It should probably reference a file on GitHub instead

**Comment by vipuldelwadia** [comment]
It is a file on Github: https://github.com/tvrenamer/tvrenamer.github.com/blob/master/version.html 😛 

Thanks @eprenamer for all the work you've done! Definitely cut a beta version, and create a release page for the new version with all the bug fixes and features you've done. I'll play with it this week, and we can probably just release it as final if we don't hear of any issues.

**Comment by vipuldelwadia** [comment]
Also, what are your thoughts @eprenamer @daveharris in calling this version 1.0, and just incrementing the number going forward (2.0, 3.0 etc)?

Alternatively, we can keep the major version as 1 and keep incrementing the minor for future releases (1.1, 1.2 etc)

**Comment by daveharris** [comment]
Yeah I think we might as well go for a `1.0`. Maybe we should have a (distributed) release party 🍰 🎉  . Out of interest @eprenamer where are you from?

@vipuldelwadia wow that's really clever of us! I thought it was still a file on your VPS like back in the day

**Comment by eprenamer** [comment]
1.0 is fine with me.  :)  I'm in Seattle, WA, USA.

**Comment by eprenamer** [comment]
I've never built an executable of TVRenamer.  Honestly, in my own branch, one of the first things I did was elimiate the launch4j stuff.

I'd be happy to make release notes, but can anyone else help out with building the release?  If not by doing it, then by documenting how to do it?

BTW, I decided to use the "findbugs" tool on the source base, and it found some stuff I'm resolving.  So I don't think it's totally done, just yet.  But, soon...

**Comment by daveharris** [comment]
I've attempted to write the release process on the wiki at https://github.com/tvrenamer/tvrenamer/wiki/Release-Process, but I haven't actually run it and most of it was done from memory. I don't expect it to be perfect.

I can't remember how one is meant to install `ant`... for example.

Update as necessary!

**Comment by vipuldelwadia** [comment]
I can try building it tonight and see if the instructions check out - on paper they look alright.

I like the launch4j stuff - it's very little overhead to the download and is a much nicer experience for Windows users than trying to run the jar (and inevitably failing because they don't have the right Java installed!). It's the same reason that we have an app bundle for macOS users. Unfortunately Linux users are left to figure things out on their own :/

@eprenamer: if you create the release notes as a draft, I can upload the built archives to it and then we can make it available as a beta version.

**Comment by eprenamer** [comment]
BTW did you ever do release notes before?  Do you have an example?  Any particular format?  Markdown?

**Comment by vipuldelwadia** [comment]
We don't have a dedicated release notes page anywhere, we just create a release on Github, e.g. https://github.com/tvrenamer/tvrenamer/releases/tag/0.7.

If you go to https://github.com/tvrenamer/tvrenamer/releases there is a button to draft a new release.

**Comment by daveharris** [comment]
We *used* to manually update the [Changelog on the Wiki](https://github.com/tvrenamer/tvrenamer/wiki/Changelog) but since GitHib came out with 'Releases' we use that instead.

@vipuldelwadia and I are in New Zealand, Auckland and Wellington respectively. I'm sure we can make something work with Hangouts on Air or something

**Comment by eprenamer** [comment]
I've been creating issues for some things I fixed but had not made issues for previously.  I think that's a good way to track what has changed (in addition to the release notes).

As you know, most of my commits did not have a user-visible effect.  They were code cleanup and organization, infrastructure, build process, efficiency, and testing.  Honestly (and slightly embarrassingly) the actual user impact is not that large.  But I'll document what I can.

**Comment by eprenamer** [comment]
OK, draft release of 1.0b1 is there now.

I have not had a chance to try to build the exe, as I keep finding little things I'd like to get into the source code.  But also because @vipuldelwadia said he was going to try out the instructions.  Were you able to try it?

**Comment by vipuldelwadia** [comment]
The draft release looks great! Huge props for all the work you've done, looking over the list of fixes/features it is certainly impressive!

The instructions look good - I used them to build the versions attached to the v1.0b1 release. We can continue iterating while the beta is out, but I think we should hold off updating the version on the site until final.

**Comment by eprenamer** [comment]
I rebuilt the releases, and did it on OS X so the Linux newline thing ( #225 ) isn't an issue.

Not sure what else I need to do.  I guess I was hoping you guys would pound on it, and/or enlist any existing users to do so.  How have you previously made a "ship/don't ship" decision?

**Comment by vipuldelwadia** [comment]
I'll have a play again this weekend, see if it looks alright and then we can just ship it.

Quick question, did you delete the original v1.0b1 tag? I thought I had created the tag at 055c62d68296c952477399ab4f587ac9b30950de but it looks like the tag now points to b647e5c2a93eec36b8b119ab36f8af1d5977166f ? In future we should just create a v1.0b2 in that case, otherwise people might log bugs and we won't know which v1.0b1 they are for.

**Comment by eprenamer** [comment]
Yes, I did.  I wanted to "move" it, but that didn't seem possible, so I deleted it and re-created it.

I'll use a new tag in the future.
