### ISSUE TITLE
Can't add folder after clearing list

### ISSUE THREAD

**Issue by vipuldelwadia** [tvrenamer/tvrenamer#218]
After clearing the list of files using the `Clear List` button, the `Add Folder` function doesn't seem to be working.

`Add files` and drag-and-drop continue to work after clearing the list.

Found in version 1.0b1 (055c62d68296c952477399ab4f587ac9b30950de).

**Comment by eprenamer** [comment]
This is related to #220 .  I had neglected to create an Issue for that previously, but now I have. 

Hopefully, you agree with that issue, that it was a bug to put the same file into the table twice.

So, the fix for #220 was that if a file was already in the table, don't add it again.  And when selected items are removed from the table, the files were removed from the data backing, and they became eligible for adding to the table again.

The problem was that the "Clear List" button went through a separate mechanism and did not update the data backing.

This does not actually match your bug report.  What I saw was independent of the method of adding (add folder, add files, drag and drop).  It only matters if the file has been added previously.  Prior to #220, "Add Folder" should still have worked fine, as long as it was a _different_ folder.

Please let me know if there are remaining issues after #220

**Comment by eprenamer** [comment]
I'm not sure I should have closed this, given that what I fixed seems like only a subset of what is described in the OP.  @vipuldelwadia do you still see issues after the commit?  If so, can you help narrow it down?

**Comment by eprenamer** [comment]
@vipuldelwadia Can you confirm if the change fixes your issue?

**Comment by vipuldelwadia** [comment]
Confirmed fixed in 1.0b3
