### ISSUE TITLE
run-linux.sh DOS EOL

### ISSUE THREAD

**Issue by j-degreef** [tvrenamer/tvrenamer#225]
Hi, 

In TVRenamer-0.7.2-gtk*.zip the run-linux.sh script has DOS (Windows) end of line.
It should be edited and saved with Unix EOL to be working.

BR and thanks for your work ;)

**Comment by eprenamer** [comment]
Hmm, the file in source code does not have this issue.  But the most recent zip file still does:

https://github.com/tvrenamer/tvrenamer/releases/tag/v1.0b1

I wonder if the problem is running "ant dist.all" from a Windows machine.

@vipuldelwadia @daveharris Any thoughts?

**Comment by vipuldelwadia** [comment]
Yep I reckon so - perhaps there is an option we can pass to ant to stop it from changing line endings?

**Comment by eprenamer** [comment]
I've created new releases, and the Linux ones have the proper newlines.  This is because I ran the build on OS X, which uses Linux-style newlines.

I suppose it should have the proper newlines even if ant is run on Windows, so I'll leave this issue open until that's resolved.  But for 1.0b1, we will have the proper newlines.

**Comment by j-degreef** [comment]
Just tested TVRenamer-1.0b1-gtk64.zip from the releases page and eol are ok.

**Comment by eprenamer** [comment]
Thanks @j-degreef !  👍   Any other feedback you could give would be great.

**Comment by eprenamer** [comment]
I updated the release process on the Wiki to say to use OSX or Linux for building the distribution.  I see no reason to try to make things work on Windows when it's not really necessary.
