### ISSUE TITLE
what is the intent of "ignore keywords"?

### ISSUE THREAD

**Issue by eprenamer** [tvrenamer/tvrenamer#310]
The preferences dialog has a field labeled "Ignore files containing ".  By default, we include the word "sample", though users can remove it.

The behavior I see is that, when we first add files to the table, we normally check the check box.  But, if the filename contains any of the "ignored" words, the check box is off by default.

Nevertheless, we go ahead and look up the episode (of the file with the ignored keyword), and if we find the information, we change the checkbox to on.

I realize by this point I've touched nearly every line of code, and I figured I might have accidentally broken it, but I went back to the 0.7 release, and looked at the source code, and that's all that happens with the "ignore keywords", there, too.

Should we actually _ignore_ those files?  Maybe we should leave them out of the table altogether, or grey them out?  Or, in any case, just don't look them up, and put in a status message like, "ignoring this file because it contains..." ?

@vipuldelwadia  @daveharris What do you think?  What was the intent of the behavior with "ignored" files?

**Comment by eprenamer** [comment]
BTW in the unlikely event anyone wants to check out the old behavior, I have the branch `previous` in the main repository that is a pretty good point to look at.  And you can always go back a bit before that, from there...

**Comment by vipuldelwadia** [comment]
The intent was to allow the user to point to a directory with more than just the tv episode files in it (for example nfo files or sample clips) and have tvrenamer pick up just the files they cared about rather than all of them. Usually these extra files were either not tv episode files (and not named in an expected format) or they were supplementary files the user typically doesn't want to rename / move.

**Comment by eprenamer** [comment]
Resolved in PR #312
