### ISSUE TITLE
Not moving files to network share

### ISSUE THREAD

**Issue by Sandriell** [tvrenamer/tvrenamer#359]
I am attempting to move/rename to a network share from a local directory. Was able to add the path correctly and it did correctly create the needed folders (show name and season) on the share, but it just doesn't make any effort to rename or move the files.

If I try just renaming, with moving disabled, it does rename just fine.

If I try renaming and moving to a local directory it does work.

If there are log files created, I have no idea where they are. I am running Windows x64.

**Comment by eprenamer** [comment]
To get log files, you need to run in debug mode:

https://github.com/tvrenamer/tvrenamer/blob/master/README.md#running-in-debug-mode

The only thing I can think of is perhaps you are not giving it enough time.  In order to "move" a file to a network share, it really has to copy the file (and then delete the original).  With video files, that can take a significant amount of time.  Could you try moving just one file, and giving it at least 30 seconds (if you haven't done so already)?

**Comment by Sandriell** [comment]
Ran it in debug mode and I am getting the following:

`2018/11/21 13:14:31,501 WARN FileUtilities#ensureWritableDirectory cannot write file to \\HDA\Recorded TV\Bob's Burgers\Season 9`
`2018/11/21 13:14:31,502 WARN FileMover#tryToMoveFile not attempting to move F:\Torrent Downloads\bobs.burgers.s09e01.720p.web.x264-tbs.mkv`

I even tried running with elevated permissions and same error. The directory absolutely is writable and I do have permission so I am not sure why it says it does not. It had no trouble creating the "Season 9" folder.

**Comment by scalablewebdesign** [comment]
Just downloaded this program because I cannot stand Filebot and TheRenamer has stopped working on Windows 10 and that developer doesn't appear interested in fixing the issue.

I just wanted to add I have the same exact problems Sandriell has when trying to rename and move files to a network share. The folder creates just fine where I've specified it to, however none of the tv episodes will move. I'm using Windows 10 x64 with the latest October update. Java is also current @ 1.8.0_201

Are the developers actively working on this program and/or issue?

**Comment by planetrocky** [comment]
Windows 10 x64 1903

Filerenamer fails on network share, folder permissions set to "Full Control" for user.

Debug log:

c:\Applications>java -jar TVRenamer-1.0b4-win64.exe
2019/12/17 13:30:58,434 WARN FileUtilities#ensureWritableDirectory cannot write file to V:\TV\showname\Season 4
2019/12/17 13:30:58,443 WARN FileMover#tryToMoveFile not attempting to move V:\TV\showname\Season 4\showname.S04E09.HDTV.x264.mkv
2019/12/17 13:30:58,443 INFO ResultsTable#finishMove failed to move item: FileEpisode {file: showname.S04E09.HDTV.x264.mkv, show: Riverdale, season: 4, episode: 9 }

**Comment by vipuldelwadia** [comment]
Just checking, do you have the correct permissions set on the destination directory? TVRenamer is reporting:
> 2019/12/17 13:30:58,434 WARN FileUtilities#ensureWritableDirectory **cannot write file to V:\TV\showname\Season 4**

**Comment by planetrocky** [comment]
Yes, all folders are set to "Full Control" for the user, and it's inherited from the root folder.

I tried to debug in Procmon from SysInternals, but tvrenamer sends thousands of strange IO calls all the way back up every folder on the network share.
