### ISSUE TITLE
Windows 10 nothing happens when attempting to install 64bit edition

### ISSUE THREAD

**Issue by KyleTryon** [tvrenamer/tvrenamer#388]
Window Version 10.0.17134 Build 17134
File: TVRenamer-0.8-win64.exe

No error or output of any kind.

**Comment by SpootDev** [comment]
Same  :(

**Comment by StephKoenig** [comment]
Have Java 8 installed?

Also it's there's v0.8b3 you can try. https://github.com/tvrenamer/tvrenamer/releases

Is worth trying as it works beautifully, shame there isn't another release to surface the many little improvements made since 2017.

**Comment by DARKFiB3R** [comment]
Same here. x86 version works fine.

**Comment by rrrevin** [comment]
Same. 64bit version does nothing. 32bit version runs fine. But that's because I have the 32bit version of Java installed. To see what version you are running you need to open the Java Control Panel.

- Open Windows Control Panel.
- Look for "Java"
  - right there you'll see what version you are running. It will show either Java (32-bit) or Java (64-bit). But lets continue and confirm.
- Select "Java"
  - This opens the Java Control Panel.
- Select the Java tab
- Select View
- Look for your "enabled" versions of Java

I have 1.8, architecture x86. That's 32 bit. x64 should(?) be listed if you have 64bit Java enabled.

If you have installed and enabled 64bit Java and it's still not working, then there is an issue. Otherwise this Git issue could probably be closed.

**Comment by StephKoenig** [comment]
Agreed I’ve tried both 33 and 64 with each java library base with no issue. I think the bigger issue is lack of releases to this very useful tool.
