### ISSUE TITLE
Rename on UNC path (\\server\share) does file copy instead of simple rename

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#58]
#### What steps will reproduce the problem?
1. Drag-and-drop some files from a \server\share-style SMB network share and use rename on them.
2. Press the rename button.
#### What is the expected output? What do you see instead?

The percent counter starts ticking for each file, which is consistent with a copy (instead of rename) operation. I'm expecting an instant rename operation. If I map the share to a drive letter and perform the same operation it does indeed perform a rename (and not a copy).
#### What version of the product are you using? On what operating system?

0.5 x64 on Windows 7.
#### What is the result of running 'java -version' on the command line?

java version "1.7.0_07"
Java(TM) SE Runtime Environment (build 1.7.0_07-b10)
Java HotSpot(TM) 64-Bit Server VM (build 23.3-b01, mixed mode)

**Comment by eprenamer** [comment]
I thought perhaps the switch to the Java NIO package ( #158 ) might have helped, but I just tested it and TVRenamer still considers a UNC path to be a different disk from a regular path, even if they ultimately resolve to the same directory.  Will require more investigation.

**Comment by eprenamer** [comment]
It's unfortunate that github provides all those silly "updates" even for commits that were made to private branches.

**Comment by eprenamer** [comment]
So, when I commented on this a year and a half ago, I was talking about a situation where you were accessing a local disk, but doing so using UNC paths.  So basically where you were accessing \\localhost\path, where that is mapped to something like C:\Path, and you were moving the files to somewhere else on C:\, using the drive letter.

When that is the case, our code which chooses whether to do a simple "rename" or a "copy and delete" chooses "copy and delete", because it believes they are different disks.

However, I've done some experimenting, and even if we DID understand they were the same disk, and if we did invoke a simple rename, Java would do a "copy and delete" anyway.  Java (at least, in NIO) does not have a "rename" functionality.  It just has "move", which will either do a rename or a copy-and-delete, at Java's discretion.

However, in the case where you're using UNC for both source and destination, in my testing it DOES work.  It does do a simple rename.

Again, my comment before referred to the very specific situation where one path was UNC and the other was drive letter, despite the fact that they ultimately referred to the same device.

I don't think we can get that to "work".  The workaround is to use a consistent way of referring to the drive.

For other cases, this was already fixed a long time ago.
