### ISSUE TITLE
Delete emptied directories when 'Move to TV Directory'

### ISSUE THREAD

**Issue by daveharris** [tvrenamer/tvrenamer#68]
When all files are moved from a directory, that directory and its parent should be deleted if they are empty so the user doesn't have to manually cleanup when putting files on a NAS or something from a temporary location

**Comment by eprenamer** [comment]
I have done this in my branch, though I didn't make it configurable (yet).

**Comment by eprenamer** [comment]
My latest change implements this, but does so unilaterally.  It doesn't give the user the option to leave the directories behind.

**Comment by eprenamer** [comment]
I have modified it so that the default is now to not delete the directories, in order to preserve the old behavior.

The functionality is there to have this behavior, but it is still not exposed to the user through the UI.

Until it's exposed via the UI, savvy users can get this behavior by editing ~/.tvrenamer/prefs.xml by hand, adding:

`  <removeEmptiedDirectories>true</removeEmptiedDirectories>`

Leaving this issue open until the behavior is exposed via the UI

**Comment by eprenamer** [comment]
Included in PR #315 

Note, this deletes emptIED directories, not necessarily empty ones.  If the user adds a folder, and the folder contains an empty subfolder, that subfolder will not be removed (regardless of setting).  This only checks directories for emptiness after a file has been moved out of it.
