### ISSUE TITLE
On launch, with move enabled on a disconnected drive, application freezes.

### ISSUE THREAD

**Issue by camsonsnarkle** [tvrenamer/tvrenamer#74]
When launching the application, when move is enabled, and the location is an external drive which is disconnected, the application will present a dialog "Couldn't create path, move is now disabled" and then the application will freeze and become unresponsive.

The only work around is to reconnect the drive, or edit the preferences file to disable move.

**Comment by digitalfaber** [comment]
Hi, any news for this bug?
I can no longer use the app after disconnecting the external drive, nor I can find the preferences file to edit on OSX.

**Comment by daveharris** [comment]
Hi,
Sorry about the lack of response.
I think I've been able to reproduce the bug and I worked out why it was
happening, but I wasn't able to come up with a fix. The problem is that the
settings get loaded before the UI, so we can't display an error message
(yet). Not quite sure how to make it show later. I also don't remember why
it freezes, it must go into some some wait loop or something.

The settings file is in your home folder, called .tvrenamer so it's hidden.


Dave

On 24/03/2015, at 5:13 am, digitalfaber <notifications@github.com> wrote:

Hi, any news for this bug?
I can no longer use the app after disconnecting the external drive, nor I
can find the preferences file to edit on OSX.

--
Reply to this email directly or view it on GitHub
<https://github.com/tvrenamer/tvrenamer/issues/74#issuecomment-85070910>.

**Comment by digitalfaber** [comment]
Thank you Dave! I found the prefs file and set back the move options to false.
This allowed me to open the app again and change the path in the app preferences panel.

**Comment by daveharris** [comment]
Awesome, glad you have it working.
I'm sorry about the lack of progress on this (and many other) bugs. I've switched to rails developer and neither myself now @vipuldelwadia have any time to devote to this. That being said, I was planning to spend some time on bugs tomorrow evening so we'll see

**Comment by eprenamer** [comment]
If I understand the issue, this should be resolved.  I tried editing my preferences to have the destDir point to a nonexistent drive.  Then I tried to start up the app.  I got a dialog box saying that it couldn't create the path, and "move" was therefore disabled.  Nothing happens while the dialog box is up.  Once I ok the dialog, the app's main UI starts up.

I think that means the bug is no longer present.  Please feel free to re-open if there's something I've missed.
