### ISSUE TITLE
"Marvels Daredevil" matches incorrectly as "Modern Marvels"

### ISSUE THREAD

**Issue by lbrunsmann** [tvrenamer/tvrenamer#84]

**Comment by vipuldelwadia** [comment]
Do you have an example input filename?

**Comment by lbrunsmann** [comment]
marvels.daredevil.s01e01.webrip.x264-2hd

**Comment by vipuldelwadia** [comment]
I've looked into this, unfortunately this is because the provider we use for episode information - TVRage - has labelled this show as just *Daredevil* instead of *Marvel's Daredevil*: http://www.tvrage.com/daredevil

As a temporary workaround, you can add this show to your tvrenamer overrides file in your home directory, on windows this is:
```
%HOMEPATH%\.tvrenameroverrides
```
More information about the overrides feature can be found in the release notes for 0.6: https://github.com/tvrenamer/tvrenamer/releases/tag/v0.6.

Note that adding the override will cause the show to be renamed to just *Daredevil* when using tvrenamer to rename.

**Comment by lbrunsmann** [comment]
Thanks so much Vipul. I have tried to put the following in but I can't get it to work, is this correct?

<entry>
      <string>Modern Marvels</string>
      <string>Daredevil</string>
</entry>

**Comment by vipuldelwadia** [comment]
Yeah I tried it myself just now but it doesn't wirk :/.

I'll have a go at switching to TheTVDB for episode info, as they don't have the problem.
