### ISSUE TITLE
Missing titles.

### ISSUE THREAD

**Issue by Spaceherpe** [tvrenamer/tvrenamer#94]
Since updating to 7b and dealing with the problem of name hosting that you tried to , I've found several shows that no longer rename and transfer. The program seems to lag then time out. 

I've listed the titles I've been having issues with:

Hawaii Five-0
NCIS
NCIS New Orleans
Once Upon a Time
Blindspot

**Comment by vipuldelwadia** [comment]
Hi there,

Could you provide the filenames that your tried to rename?

**Comment by Spaceherpe** [comment]
I already renamed them manually, but I'll e-mail you the next titles that
don't work.

**Comment by Spaceherpe** [comment]
Found three more today that wouldn't rename. These are also the same titles
that wouldn't rename previously...

law.and.order.svu.1705.hdtv-lol

Marvels.Agents.of.S.H.I.E.L.D.S03E03.HDTV.x264-FLEET

ncis.1304.hdtv-lol

**Comment by finalito** [comment]
I've always problems then i try to rename also Marvels, file name is

Marvels.Agents.of.S.H.I.E.L.D.S03E10.HDTV.x264-KILLERS

**Comment by daveharris** [comment]
Hi,

By running the app in debug mode and looking at the URL produced, I've determined why the files aren't being matched.

1. `law.and.order.svu.1705.hdtv-lol`
The URL we lookup is http://www.thetvdb.com/api/GetSeries.php?seriesname=law%20and%20order%20svu%201. Notice the `svu%201` on the end. I think that's because we think the show name is `law and order svu 1`, season 7 episode 5 rather than season *17*. We'll need to fix the pattern matching for this case

2. `Marvels.Agents.of.S.H.I.E.L.D.S03E03.HDTV.x264-FLEET`
The URL again is wrong here. We lookup http://www.thetvdb.com/api/GetSeries.php?seriesname=marvels%20agents%20of%20s%20h%20i%20e%20l%20d which evaluates as `http://www.thetvdb.com/api/GetSeries.php?seriesname=marvels agents of s h i e l d`. We are replacing periods with spaces in the title. If we don't do this, we would get the right result, i.e. http://www.thetvdb.com/api/GetSeries.php?seriesname=Marvel%27s%20Agents%20of%20S.H.I.E.L.D.

3. `ncis.1304.hdtv-lol`
This is the same problem as number 1. We look up http://www.thetvdb.com/api/GetSeries.php?seriesname=ncis%201

@vipuldelwadia, I imagine that number 1 and 3 are relatively easy to fix. Not so sure about number 2?

Thanks for the comments @Spaceherpe and @finalito. I imagine that the extraneous `%201` was being ignored by tvrage.com but not by thetvdb.com

**Comment by Spaceherpe** [comment]
Dave,

Thanks for responding. For the most part, I've found a slight fix, but it
involves me going into each title and ensureing that 108 reads s01e08. It's
not the biggest deal as the majority of shows rename just fine. I really
appreciate all you are doing for this program! I use it almost daily and
love it!

~Space

**Comment by daveharris** [comment]
Hi @Spaceherpe,

I'm glad you have semi-solution. I have another one which is probably no better, but maybe it will.

There is a totally undocumented feature (!) where if the filename doesn't contain the show name, we look at the directory name ([see insertShowNameIfNeeded()](https://github.com/tvrenamer/tvrenamer/blob/9b44e056526ec263561a40152b8d46f40e0c7a9a/src/main/com/google/code/tvrenamer/controller/TVRenamer.java#L74))

So if you have the folder structure `Marvels Agents of SHIELD/S03E03.HDTV.x264-FLEET` then it searches thetvdb.com for 'Marvels Agents of SHIELD'. Now the renamed works fine. Unfortunately this only works if the `SHIELD` part doesn't contain any periods, otherwise they are escaped as before.

I realise that this is more work than before but might help you with some weirdly names shows in the future.

What we **should** be doing is if we get no results (`<Data></Data>`) from thetvdb.com then we should retrieve the show name from the parent directory and perform the search again. Then you wouldn't need to do anything and it would work like magic

Dave

**Comment by Spaceherpe** [comment]
If I'm understanding you correctly, and I'm no coder, this looks at the
file folder naming convention? This doesn't really help me, as many of the
folder names are just as messed up.

Like I said, I'm no coder. I do my best to keep it simple. I use the
program to rename and move what it recognizes and fix the rest manually.
