### ISSUE TITLE
Method for renaming files on remote server

### ISSUE THREAD

**Issue by Paradoxum** [tvrenamer/tvrenamer#96]
Hi,

So I've got a Plex server in my house on my LAN.

If I add a directory to TVRenamer and hit rename, what it appears to do is something like copy the file somewhere temporarily and then rename it and remove the old version - this can take some time when renaming a lot of files on my server, wheras other TV Renamer utilities i've used simply rename the file without doing anything else to it, is there any way I can do that with this? The options menu is not very comprehensive so I couldn't find anything in there.

Thanks,
para

**Comment by Paradoxum** [comment]
I just noticed what I think is the same issue posted here:

https://github.com/tvrenamer/tvrenamer/issues/58

**Comment by daveharris** [comment]
Hi @Paradoxum,

Looking at the code, I see there are 2 paths it follows, depending on the result of `areSameDisk()` ([source](https://github.com/tvrenamer/tvrenamer/blob/9b44e056526ec263561a40152b8d46f40e0c7a9a/src/main/com/google/code/tvrenamer/controller/FileMover.java#L92)). If `true` it just calls `File.renameTo()`, otherwise it calls into `FileUtilities.moveFile`.

I took a look at the [commit comments](https://github.com/tvrenamer/tvrenamer/commit/287bd3928ee68728e0199164735840bd6db1376e) which @vipuldelwadia wrote for this change. It looks like calling `File.renameTo()` is unreliable on non-Windows. Maybe @vipuldelwadia can shed some light but it doesn't look like there is anything we can do...

Dave

**Comment by eprenamer** [comment]
I do not use Plex myself.  I looked into it.  It mostly wants to hide any details from the user.  It doesn't really expose the filenames, as far as I can see.  I saw something about being able to access the files, but all it really said was set it up to use SMB.

I think we have it working so that files accessed via SMB, and moved onto the same device, will do the simple rename.

I'm assuming @Paradoxum may no longer be interested, but if anyone still has issues with this with the 0.9 release, I assume they will either re-open this or create a new issue.
